name: Add issues to the project
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@2e5cc851ca7162e9eb510e6da6a5c64022e606a7 # v1.0.0
        with:
          project-url: https://github.com/orgs/ministryofjustice/projects/17
          github-token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
