name: Add issues to the project
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/ministryofjustice/projects/17
          github-token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
