name: Send Message on Onboarding Issue Close

on:
  issues:
    types:
      - closed
jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Send message to user on onboarding issue close
        env:
          SECRET: ${{ secrets.GITHUB_TOKEN }}

